apiVersion: rbac.authorization.k8s.io/v1
kind: pendings
metadata:
  creationTimestamp: null
  name: admin
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: gitops
